### ISSUE TITLE
Continuously test fpm with latest TOML Fortran

### ISSUE THREAD

**Issue by awvwgk** [toml-f/toml-f#125]
Add an integration test to ensure TOML Fortran is not breaking functionality in fpm.

cc Minh @minhqdao

**Comment by urbanjost** [comment]
When I saw the new version release,  I just commented out the version in the fpm.toml file in the latest released fpm and built it and got/src/fpm/cmd/new.f90:666:13:

  666 |     ser%unit=lun
      |             1
Error: ‘unit’ at (1) is not a member of the ‘toml_visitor’ structure
compilation terminated due to -fmax-errors=1.
<ERROR> Compilation failed for object " src_fpm_cmd_new.f90.o "
<ERROR>stopping due to failed compilation

is that to be expected?

**Comment by awvwgk** [comment]
Yes, that is expected, I broke the API for the serialization in #127. I'll open an issue in fpm.
